name: Deploy aab to artifact

on:
  push:
    branches:
      - main
    tags:
      - 't*'

jobs:
  Gradle:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: setup jdk
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: wrapper
      - name: Build
        run: |
          chmod +x ./gradlew  
          ./gradlew build -x lint -x test --no-daemon
      - name: Sign Release
        run: |
          ./gradlew app:assembleRelease
      - name: Upload build APK
        uses: actions/upload-artifact@v4
        with:
          name: App bundle(s) and APK(s) generated
          path: app/build/outputs/
      - name: Gotify Notification
        uses: eikendev/gotify-action@master
        with:
          gotify_api_base: '${{ secrets.gotify_api_base }}'
          gotify_app_token: '${{ secrets.gotify_app_token }}'
          notification_title: 'Build ${GITHUB_REF_NAME} #${GITHUB_RUN_NUMBER}'
          notification_message: 'Commit: ${COMMIT_SHA_SHORT}\nStatus: ${{ job.status }}\nActor: ${{ github.actor }}\nBuild URL: $GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID'
          notification_priority: 0