name: Deploy aab to artifact

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  Gradle:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: setup jdk
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
          cache: gradle
      - name: Extract existing version code
        run: |
          # Extract version number from branch name
          version_name=${GITHUB_REF#refs/tags/v}
          
          # Get existing version code from build.gradle
          version_code=$(grep "versionCode" app/build.gradle.kts | awk '{print $3}' | tr -d '\n')
          
          # Increment existing version code by 1
          version_code=$((version_code + 1))
          
          # Set environment variable for later use
          echo "VERSION_NAME=$version_name" >> $GITHUB_ENV
          echo "VERSION_CODE=$version_code" >> $GITHUB_ENV
      - name: Increase version code and change version name
        run: |
          # Update build.gradle with new version code and name
          echo "${{ env.VERSION_CODE }} - ${{ env.version_name }}"
          sed -i "s/versionCode [0-9]\+/versionCode ${{ env.VERSION_CODE }}/g" app/build.gradle.kts
          sed -i "s/versionName \"[^\"]*\"/versionName \"${{ env.VERSION_NAME }}\"/g" app/build.gradle.kts

      - name: Commit and push changes
        run: |
          git config user.email "github-actions@github.com"
          git config user.name "Github Actions"
          git commit -am "Bump version code and change version name"
          git push origin HEAD

      - name: Open pull request
        uses: peter-evans/create-pull-request@v6.0.2
        with:
          commit-message: "Bumping to ${{ env.VERSION_CODE }}"
          branch: "${{ github.ref }}"
          title: "${{ env.VERSION_NAME }} - (${{ env.VERSION_CODE }})"
          body: "${{ env.VERSION_NAME }} - (${{ env.VERSION_CODE }})"
          base: "main"
#      - name: Build
#        run: |
#          chmod +x ./gradlew
#          ./gradlew build -x lint -x test --no-daemon
#      - name: Sign Release
#        run: |
#          ./gradlew app:assembleRelease
#      - name: Upload build APK
#        uses: actions/upload-artifact@v4
#        with:
#          name: App bundle(s) and APK(s) generated
#          path: app/build/outputs/