name: Deploy aab to artifact

on:
  push:
    branches:
      - main
    tags:
      - 't*'

jobs:
  Gradle:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: setup jdk
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: wrapper
      - name: Build
        run: |
          chmod +x ./gradlew  
          ./gradlew build -x lint -x test --no-daemon
      - name: Sign Release
        run: |
          ./gradlew app:assembleRelease
      - name: Upload build APK
        uses: actions/upload-artifact@v4
        with:
          name: App bundle(s) and APK(s) generated
          path: app/build/outputs/
